### ISSUE TITLE
How to implement onEndReached ?

### ISSUE THREAD

**Issue by bohdan145** [FSPinho/react-native-speedy-list#2]
When I pass my onScroll event to ScrollViewProps, it overwrites the default onScroll, so scrolling logic stops working

**Comment by FSPinho** [comment]
Hi, @bohdan145 

Please, try the latest version. I've fixed this in [**this commit**](https://github.com/FSPinho/react-native-speedy-list/commit/02108dd19d417588d9d470733411444933d94873).

Thanks for your comment.

**Comment by bohdan145** [comment]
Now it works, thanks @FSPinho

**Comment by ViktorVojtek** [comment]
Hello, it doesn't seems to work for me even in the latest version. Could you please explain how to use onEndReached function or extend the readme file?

Thanks.
