### ISSUE TITLE
Missing onEndReached prop

### ISSUE THREAD

**Issue by ViktorVojtek** [FSPinho/react-native-speedy-list#5]
Hello, onEndReached doesn't seems to work for me even in the latest version. Could you please explain how to use onEndReached function or let me know if it's implemented in your package?

Thanks.

_Originally posted by @ViktorVojtek in https://github.com/FSPinho/react-native-speedy-list/issues/2#issuecomment-1170081723_

**Comment by FSPinho** [comment]
Hi @ViktorVojtek.

Thanks for catching this. I've just added this prop to the component. Let me know if you have more improvements to suggest.

Cheers,
Felipe

**Comment by ViktorVojtek** [comment]
Hi Felipe (@FSPinho).

Thanks I appreciate your update, works like a charm :) 

May I have one more request? Could you please add "onRefresh" prop also?
So user would be able to refresh the whole list?

Thanks,
Viktor
